# Generated by Django 5.2.4 on 2025-07-06 00:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanningBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="PRODUCTION PLANNING CONTROL DISPLAY BOARD",
                        max_length=200,
                    ),
                ),
                ("meeting_time", models.TimeField(blank=True, null=True)),
                ("today_date", models.DateField(default=django.utils.timezone.now)),
                ("tomorrow_date", models.DateField()),
                ("next_day_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OtherInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_name", models.CharField(max_length=100)),
                ("qty", models.IntegerField()),
                ("target_date", models.DateField()),
                ("remarks", models.TextField(blank=True)),
                (
                    "planning_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_info",
                        to="planning_board.planningboard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NextDayPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("a_shift", models.IntegerField(blank=True, null=True)),
                ("b_shift", models.IntegerField(blank=True, null=True)),
                ("c_shift", models.IntegerField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "planning_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_day_plans",
                        to="planning_board.planningboard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExcelUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/excel/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "planning_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excel_uploads",
                        to="planning_board.planningboard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CriticalPartStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_name", models.CharField(max_length=100)),
                ("supplier", models.CharField(max_length=100)),
                ("plan_qty", models.IntegerField()),
                ("receiving_time", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "planning_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="critical_parts",
                        to="planning_board.planningboard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AFMPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("FCIN", "FCIN (MNS)"), ("IU", "I/U")], max_length=10
                    ),
                ),
                ("part_name", models.CharField(max_length=100)),
                ("part_number", models.CharField(blank=True, max_length=50)),
                ("plan_qty", models.IntegerField()),
                ("remarks", models.TextField(blank=True)),
                (
                    "planning_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="afm_plans",
                        to="planning_board.planningboard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.CharField(max_length=100)),
                ("a_shift_model", models.CharField(blank=True, max_length=100)),
                ("a_shift_plan", models.IntegerField(blank=True, null=True)),
                ("a_shift_actual", models.IntegerField(blank=True, null=True)),
                ("a_shift_plan_change", models.IntegerField(blank=True, null=True)),
                ("a_shift_time", models.TimeField(blank=True, null=True)),
                ("a_shift_remarks", models.TextField(blank=True)),
                ("b_shift_model", models.CharField(blank=True, max_length=100)),
                ("b_shift_plan", models.IntegerField(blank=True, null=True)),
                ("b_shift_actual", models.IntegerField(blank=True, null=True)),
                ("b_shift_plan_change", models.IntegerField(blank=True, null=True)),
                ("b_shift_time", models.TimeField(blank=True, null=True)),
                ("b_shift_remarks", models.TextField(blank=True)),
                ("c_shift_model", models.CharField(blank=True, max_length=100)),
                ("c_shift_plan", models.IntegerField(blank=True, null=True)),
                ("c_shift_actual", models.IntegerField(blank=True, null=True)),
                ("c_shift_plan_change", models.IntegerField(blank=True, null=True)),
                ("c_shift_remarks", models.TextField(blank=True)),
                (
                    "planning_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_lines",
                        to="planning_board.planningboard",
                    ),
                ),
            ],
            options={
                "ordering": ["line_number"],
            },
        ),
        migrations.CreateModel(
            name="SPDPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer",
                    models.CharField(
                        choices=[
                            ("MSIL", "MSIL"),
                            ("HMSI", "HMSI"),
                            ("IYM", "IYM/PIAGGIO"),
                            ("HMCL", "HMCL"),
                        ],
                        max_length=20,
                    ),
                ),
                ("part_name", models.CharField(max_length=100)),
                ("part_number", models.CharField(blank=True, max_length=50)),
                ("plan_qty", models.IntegerField()),
                ("remarks", models.TextField(blank=True)),
                (
                    "planning_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spd_plans",
                        to="planning_board.planningboard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TomorrowPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("a_shift", models.IntegerField(blank=True, null=True)),
                ("b_shift", models.IntegerField(blank=True, null=True)),
                ("c_shift", models.IntegerField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "planning_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tomorrow_plans",
                        to="planning_board.planningboard",
                    ),
                ),
            ],
        ),
    ]
