# Generated by Django 5.2.4 on 2025-09-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planning_board", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productionline",
            options={"ordering": []},
        ),
    ]
